name: halal_food_delivery
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # iOS-style icons
  get: ^4.7.2             # State management & navigation
  http: ^1.1.0            # HTTP requests
  intl: ^0.18.1           # Internationalization
  logger: ^2.0.1          # Logging
  url_launcher: ^6.1.12   # Open URLs
  google_fonts: ^6.2.1    # Custom fonts
  shared_preferences: ^2.3.2  # Local storage
  lottie: ^3.3.1         # Lottie animations
  pin_code_fields: ^8.0.1 # OTP input fields

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0   # Linting rules

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/